spring:
  config:
    import: default.yml

  datasource:
    url: jdbc:mysql://localhost:3306/divide
    username: divide
    password: divide

  jpa:
    hibernate:
      ddl-auto: create

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher