spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        sql: debug

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-valid-time-in-seconds: 1000000

